# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'Calculator' do
  # Comment the next line if you don't want to use dynamic frameworks
  # Pods for Calculator
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
end 

target 'CalculatorTests' do
  inherit! :search_paths
  # Pods for testing

  pod 'RxBlocking', '~> 5'
  pod 'RxTest', '~> 5'
end
